### PR TITLE
About us updated in #40

### PR DESCRIPTION
**Pull request by Merine303**
the dummy texts have been replaced, team members names and position updated

### CODE REVIEW

**Review by Fenn-CS — CHANGES_REQUESTED** [review]
Please, 

- Fix lint issues, look at the lint section of the readme
- We can't just add content like this, we need to use translation files and add the content in french and english

See #20 and #11

**Comment by Merine303** [comment]
> Please,
> 
> * Fix lint issues, look at the lint section of the readme
> * We can't just add content like this, we need to use translation files and add the content in french and english
> 
> See #20 and #11
> 
> Thank you!

ok thanks for the feedback

**Comment by Fenn-CS** [comment]
@ExcelDurant You can help him fix this, when you have less on your plate?

**Comment by ExcelDurant** [comment]
> > Please,
> > 
> > * Fix lint issues, look at the lint section of the readme
> > * We can't just add content like this, we need to use translation files and add the content in french and english
> > 
> > See #20 and #11
> > Thank you!
> 
> ok thanks for the feedback

@Merine303  At what level are you with this? I can help

**Pull request closed without merging**
